### ISSUE TITLE
VMTableViewController

### ISSUE THREAD

**Issue by imdp6** [yangKJ/Rickenbacker#1]
继承VMTableViewController怎么修改public private(set) var style: UITableView.Style = UITableView.Style.plain
我想用insetGrouped怎么办呢

**Comment by yangKJ** [comment]
初始化的时候就有提供这个参数

**Comment by imdp6** [comment]
post请求怎么拼接后面参数呀

**Comment by imdp6** [comment]
如果是collectionView怎么刷新呢

**Comment by yangKJ** [comment]
> 



> post请求怎么拼接后面参数呀

这个你去使用RxNetworks网络库啊！！！

**Comment by yangKJ** [comment]
> 如果是collectionView怎么刷新呢

CollectionView也是ScrollView子类，去抄`VMTableViewController`的实现方式
自己实现一个类似的子类
