### ISSUE TITLE
Xcode14.0报错

### ISSUE THREAD

**Issue by imdp6** [yangKJ/Rickenbacker#2]
<img width="593" alt="Screen Shot 2022-09-14 at 10 36 36" src="https://user-images.githubusercontent.com/28843198/190046010-668b615f-ddf1-4dd9-8d26-cef088df2efe.png">

**Comment by kb100824** [comment]
@yangKJ  你可以参考这里 https://github.com/CocoaPods/CocoaPods/issues/11402
